### ISSUE TITLE
training parameter

### ISSUE THREAD

**Issue by kazuki-can** [nixingyang/FlipReID#11]
Hi, I'm kazuki-can.
Thanks for your attractive work.
Since I'm going to write a paper about Computer Vision with this repository, I would like to know its training parameter.
I use the model file called "Market1501_resnesta50_18209984.h5".

Thank you.

**Comment by nixingyang** [comment]
Hi,
Thanks for your interest in our work.
I suggest trying to reproduce the model we have obtained. It should be quite straightforward. Please follow the instructions in the [README.md](https://github.com/nixingyang/FlipReID/blob/master/README.md) file. The code works as it is, while the non-default training hyper-parameters are explicitly specified in the command.
All the best.
Xingyang Ni

**Comment by kazuki-can** [comment]
I followed your instructions and it seems worked.
Thank you very much.
