### ISSUE TITLE
Is it possible to remember gallery features and calculate the distance ?

### ISSUE THREAD

**Issue by kazuki-can** [nixingyang/FlipReID#12]
Hello again.
Thank you for supporting me every time.

I've used this model so far and it's quite amazing.
But as I wrote codes like #3 you helped me before, the process time takes a bit long when there are over thousands of query images because it calculate all gallery features each time when one of query features.
So now, I want to write codes like 

1. calculate gallery features
2. calculate query features
3. compute the distances between 1 and 2

Is it possible to write codes like this?

Thank you

**Comment by nixingyang** [comment]
Yes.
What you have proposed is the correct approach, and the features of one test sample should be calculated only once.
This is also how the existing code is implemented. Please check this [snippet](https://github.com/nixingyang/FlipReID/blob/1b5b241ece4d86bcd73e18658176a8c9b233f63c/solution.py#L611-L613) for more details.
Xingyang

**Comment by kazuki-can** [comment]
Thank you for your prompt response.
I'll write codes , refering to your instructions.

Thank you

**Comment by FatemehAnvari** [comment]
@kazuki-can 
Hi. I am glad that you were able to run this project
But I have the problem of incompatibility between the versions and I can't run Google colab
Can you guide me?
