### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by Peanut736** [nixingyang/FlipReID#14]
hi, i use the h5 file you offered to test, but i dont get the map and the rank1. Thats my result: 
![image](https://user-images.githubusercontent.com/52313103/221403241-81914c71-b555-4a4e-8794-af10c7bc0428.png)

loss 7.887027
tf_op_layer_RealDiv_2_loss 0.002644
tf_op_layer_RealDiv_3_loss 0.002606
tf_op_layer_RealDiv_4_loss 0.001227
classification_model_loss 0.036024
classification_model_1_loss 0.025743
classification_model_2_loss 0.019219
flipping 0.007067
global_ge_m_pooling2d_power 1.506939
global_ge_m_pooling2d_1_power 1.916795
global_ge_m_pooling2d_2_power 1.848862
1/1 - 2s - loss: 7.8870 - tf_op_layer_RealDiv_2_loss: 0.0026 - tf_op_layer_RealDiv_3_loss: 0.0026 - tf_op_layer_RealDiv_4_loss: 0.0012 - classification_model_loss: 0.0360 - classification_model_1_loss: 0.0257 - classification_model_2_loss: 0.0192 - flipping: 0.0071 - global_ge_m_pooling2d_power: 1.5069 - global_ge_m_pooling2d_1_power: 1.9168 - global_ge_m_pooling2d_2_power: 1.8489
All done!

just loss, i cant find the map and rank1.

**Comment by nixingyang** [comment]
Hi,
Thank you for your interest in our work.
Have you followed the guide in the [Evaluation](https://github.com/nixingyang/FlipReID#evaluation) section? You need to append the `evaluation_only` argument.
If you still have this issue, please provide the complete log.
All the best.
Xingyang Ni

**Comment by Peanut736** [comment]
Getting hyperparameters ...
Using command solution.py --dataset_name Market1501 --root_folder_path /project/zhanghong/fast-reid_tutorial/datasets/ --backbone_model_name resnesta50 --pretrained_model_file_path ../Market1501.h5 --use_re_ranking --use_horizontal_flipping_inside_model --use_horizontal_flipping_in_evaluation --output_folder_path evaluation_only --evaluation_only --freeze_backbone_for_N_epochs 0 --testing_size 1.0 --evaluate_testing_every_N_epochs 2
? False
alsologtostderr False
backbone_model_name resnesta50
beta_regularization_factor 0.0005
bias_regularization_factor 0.0005
dataset_name Market1501
epoch_num 2
evaluate_testing_every_N_epochs 2
evaluation_only True
freeze_backbone_for_N_epochs 0
gamma_regularization_factor 0.0005
help False
helpfull False
helpshort False
helpxml False
identity_num_per_batch 4
image_height 384
image_num_per_identity 4
image_width 128
kernel_regularization_factor 0.0005
learning_rate_base 0.0002
learning_rate_drop_factor 10.0
learning_rate_end 0.0002
learning_rate_lower_bound 2e-06
learning_rate_mode default
learning_rate_start 0.0002
learning_rate_steady_epochs 30
learning_rate_warmup_epochs 10
log_dir 
logger_levels {}
logtostderr False
max_value 1.0
min_value 0.0
only_check_args False
op_conversion_fallback_to_while_loop False
output_folder_path evaluation_only
patch_replacement_probability 0.8
pdb False
pdb_post_mortem False
pooling_mode GeM
pretrained_model_file_path /project/zhanghong/FlipReID-master/Market1501.h5
profile_file None
random_erasing_probability 0.8
region_num 2
root_folder_path /project/zhanghong/fast-reid_tutorial/datasets/
run_with_pdb False
run_with_profiling False
save_data_to_disk False
showprefixforinfo True
stderrthreshold fatal
steps_per_epoch 2
test_random_seed 301
test_randomize_ordering_seed 
test_srcdir 
test_tmpdir /tmp/absl_testing
testing_size 1.0
use_cprofile_for_profiling True
use_data_augmentation_in_training True
use_horizontal_flipping_in_evaluation True
use_horizontal_flipping_inside_model True
use_re_ranking True
v 0
verbosity 0
workers 2
xml_output_file 
Recreating the output folder at ../evaluation_only/Market1501_resnesta50 ...
Loading the annotations of the Market1501 dataset ...
Use ../fast-reid_tutorial/datasets/ as root_folder_path ...
Initiating the model ...
2023-02-26 15:48:39.753297: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2023-02-26 15:48:39.949300: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:06:00.0 name: Tesla V100-SXM2-16GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 15.78GiB deviceMemoryBandwidth: 836.37GiB/s
2023-02-26 15:48:39.952226: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /project/zhanghong/anaconda3/envs/torch171/lib/python3.7/site-packages/cv2/../../lib64:/software/nvidia/cuda/10.0/lib64
2023-02-26 15:48:39.954068: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10'; dlerror: libcublas.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /project/zhanghong/anaconda3/envs/torch171/lib/python3.7/site-packages/cv2/../../lib64:/software/nvidia/cuda/10.0/lib64
2023-02-26 15:48:39.956358: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /project/zhanghong/anaconda3/envs/torch171/lib/python3.7/site-packages/cv2/../../lib64:/software/nvidia/cuda/10.0/lib64
2023-02-26 15:48:39.957844: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /project/zhanghong/anaconda3/envs/torch171/lib/python3.7/site-packages/cv2/../../lib64:/software/nvidia/cuda/10.0/lib64
2023-02-26 15:48:39.959302: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /project/zhanghong/anaconda3/envs/torch171/lib/python3.7/site-packages/cv2/../../lib64:/software/nvidia/cuda/10.0/lib64
2023-02-26 15:48:39.960713: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10'; dlerror: libcusparse.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /project/zhanghong/anaconda3/envs/torch171/lib/python3.7/site-packages/cv2/../../lib64:/software/nvidia/cuda/10.0/lib64
2023-02-26 15:48:40.428506: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2023-02-26 15:48:40.428583: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1598] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2023-02-26 15:48:40.455708: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2023-02-26 15:48:41.219072: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2399955000 Hz
2023-02-26 15:48:41.246607: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x838ac80 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2023-02-26 15:48:41.246700: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2023-02-26 15:48:41.274528: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-02-26 15:48:41.274583: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      
Specifying regularizers for inference_model ...
2023-02-26 15:48:57.607688: W tensorflow/python/util/util.cc:329] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
{'Conv2D:kernel_regularizer': 124, 'BatchNorm:gamma_regularizer': 84, 'BatchNorm:beta_regularizer': 84, 'Conv2D:bias_regularizer': 40}
Added 332 regularization terms.
Specifying regularizers for classification_model ...
{'BatchNormalization:gamma_regularizer': 3, 'BatchNormalization:beta_regularizer': 3, 'Dense:kernel_regularizer': 3}
Added 9 regularization terms.
Summarizing training_model_47038201300880 ...
Model: "training_model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_11 (InputLayer)           [(None, 384, 128, 3) 0                                            
__________________________________________________________________________________________________
inference_model (Model)         [(None, 2048), (None 79429571    input_11[0][0]                   
                                                                 tf_op_layer_ReverseV2[0][0]      
__________________________________________________________________________________________________
tf_op_layer_ReverseV2 (TensorFl [(None, 384, 128, 3) 0           input_11[0][0]                   
__________________________________________________________________________________________________
tf_op_layer_AddV2 (TensorFlowOp [(None, 2048)]       0           inference_model[1][0]            
__________________________________________________________________________________________________
tf_op_layer_AddV2_2 (TensorFlow [(None, 1024)]       0           inference_model[1][1]            
__________________________________________________________________________________________________
tf_op_layer_AddV2_4 (TensorFlow [(None, 1024)]       0           inference_model[1][2]            
__________________________________________________________________________________________________
tf_op_layer_AddV2_1 (TensorFlow [(None, 2048)]       0           tf_op_layer_AddV2[0][0]          
                                                                 inference_model[2][0]            
__________________________________________________________________________________________________
tf_op_layer_AddV2_3 (TensorFlow [(None, 1024)]       0           tf_op_layer_AddV2_2[0][0]        
                                                                 inference_model[2][1]            
__________________________________________________________________________________________________
tf_op_layer_AddV2_5 (TensorFlow [(None, 1024)]       0           tf_op_layer_AddV2_4[0][0]        
                                                                 inference_model[2][2]            
__________________________________________________________________________________________________
tf_op_layer_RealDiv_2 (TensorFl [(None, 2048)]       0           tf_op_layer_AddV2_1[0][0]        
__________________________________________________________________________________________________
tf_op_layer_RealDiv_3 (TensorFl [(None, 1024)]       0           tf_op_layer_AddV2_3[0][0]        
__________________________________________________________________________________________________
tf_op_layer_RealDiv_4 (TensorFl [(None, 1024)]       0           tf_op_layer_AddV2_5[0][0]        
__________________________________________________________________________________________________
classification_model (Model)    [(None, 751), (None, 3092480     tf_op_layer_RealDiv_2[0][0]      
                                                                 tf_op_layer_RealDiv_3[0][0]      
                                                                 tf_op_layer_RealDiv_4[0][0]      
__________________________________________________________________________________________________
tf_op_layer_SquaredDifference ( [(None, 2048)]       0           inference_model[2][0]            
                                                                 inference_model[1][0]            
__________________________________________________________________________________________________
tf_op_layer_Mean (TensorFlowOpL [(None,)]            0           tf_op_layer_SquaredDifference[0][
__________________________________________________________________________________________________
tf_op_layer_SquaredDifference_1 [(None, 1024)]       0           inference_model[2][1]            
                                                                 inference_model[1][1]            
__________________________________________________________________________________________________
tf_op_layer_Mean_1 (TensorFlowO [()]                 0           tf_op_layer_Mean[0][0]           
__________________________________________________________________________________________________
tf_op_layer_Mean_2 (TensorFlowO [(None,)]            0           tf_op_layer_SquaredDifference_1[0
__________________________________________________________________________________________________
tf_op_layer_SquaredDifference_2 [(None, 1024)]       0           inference_model[2][2]            
                                                                 inference_model[1][2]            
__________________________________________________________________________________________________
tf_op_layer_AddV2_6 (TensorFlow [()]                 0           tf_op_layer_Mean_1[0][0]         
__________________________________________________________________________________________________
tf_op_layer_Mean_3 (TensorFlowO [()]                 0           tf_op_layer_Mean_2[0][0]         
__________________________________________________________________________________________________
tf_op_layer_Mean_4 (TensorFlowO [(None,)]            0           tf_op_layer_SquaredDifference_2[0
__________________________________________________________________________________________________
tf_op_layer_AddV2_7 (TensorFlow [()]                 0           tf_op_layer_AddV2_6[0][0]        
                                                                 tf_op_layer_Mean_3[0][0]         
__________________________________________________________________________________________________
tf_op_layer_Mean_5 (TensorFlowO [()]                 0           tf_op_layer_Mean_4[0][0]         
__________________________________________________________________________________________________
tf_op_layer_AddV2_8 (TensorFlow [()]                 0           tf_op_layer_AddV2_7[0][0]        
                                                                 tf_op_layer_Mean_5[0][0]         
__________________________________________________________________________________________________
add_metric (AddMetric)          ()                   0           tf_op_layer_AddV2_8[0][0]        
__________________________________________________________________________________________________
tf_op_layer_Mul (TensorFlowOpLa [()]                 0           tf_op_layer_AddV2_8[0][0]        
__________________________________________________________________________________________________
add_loss (AddLoss)              ()                   0           tf_op_layer_Mul[0][0]            
==================================================================================================
Total params: 82,522,051
Trainable params: 82,422,147
Non-trainable params: 99,904
__________________________________________________________________________________________________
Summarizing inference_model_47038158963344 ...
Model: "inference_model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            [(None, 384, 128, 3) 0                                            
__________________________________________________________________________________________________
preprocess_input (Model)        (None, 384, 128, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
features/init_block (Model)     (None, 96, 32, 64)   29024       preprocess_input[1][0]           
__________________________________________________________________________________________________
features/stage1 (Model)         (None, 96, 32, 256)  238688      features/init_block[1][0]        
__________________________________________________________________________________________________
features/stage2 (Model)         (None, 48, 16, 512)  1329408     features/stage1[1][0]            
__________________________________________________________________________________________________
features/stage3 (Model)         (None, 24, 8, 1024)  7721728     features/stage2[1][0]            
__________________________________________________________________________________________________
features/stage4_regional_branch (None, 24, 8, 2048)  16179968    features/stage3[1][0]            
__________________________________________________________________________________________________
lambda_1 (Lambda)               (None, 12, 8, 2048)  0           features/stage4_regional_branch[1
__________________________________________________________________________________________________
lambda_3 (Lambda)               (None, 12, 8, 2048)  0           features/stage4_regional_branch[1
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 12, 8, 1024)  18875392    lambda_1[0][0]                   
__________________________________________________________________________________________________
conv2d_1 (Conv2D)               (None, 12, 8, 1024)  18875392    lambda_3[0][0]                   
__________________________________________________________________________________________________
features/stage4_global_branch ( (None, 24, 8, 2048)  16179968    features/stage3[1][0]            
__________________________________________________________________________________________________
activation (Activation)         (None, 12, 8, 1024)  0           conv2d[0][0]                     
__________________________________________________________________________________________________
activation_1 (Activation)       (None, 12, 8, 1024)  0           conv2d_1[0][0]                   
__________________________________________________________________________________________________
global_ge_m_pooling2d (GlobalGe (None, 2048)         1           features/stage4_global_branch[1][
__________________________________________________________________________________________________
global_ge_m_pooling2d_1 (Global (None, 1024)         1           activation[0][0]                 
__________________________________________________________________________________________________
global_ge_m_pooling2d_2 (Global (None, 1024)         1           activation_1[0][0]               
__________________________________________________________________________________________________
lambda (Lambda)                 (None, 2048)         0           global_ge_m_pooling2d[0][0]      
__________________________________________________________________________________________________
lambda_2 (Lambda)               (None, 1024)         0           global_ge_m_pooling2d_1[0][0]    
__________________________________________________________________________________________________
lambda_4 (Lambda)               (None, 1024)         0           global_ge_m_pooling2d_2[0][0]    
==================================================================================================
Total params: 79,429,571
Trainable params: 79,337,859
Non-trainable params: 91,712
__________________________________________________________________________________________________
Summarizing preprocess_input_47038060185680 ...
Model: "preprocess_input"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_2 (InputLayer)         [(None, 384, 128, 3)]     0         
_________________________________________________________________
tf_op_layer_RealDiv (TensorF multiple                  0         
_________________________________________________________________
tf_op_layer_BiasAdd (TensorF multiple                  0         
_________________________________________________________________
tf_op_layer_RealDiv_1 (Tenso multiple                  0         
=================================================================
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
Summarizing features/init_block_47038059976848 ...
Model: "features/init_block"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_3 (InputLayer)         [(None, 384, 128, 3)]     0         
_________________________________________________________________
conv1 (ConvBlock)            (None, 192, 64, 32)       992       
_________________________________________________________________
conv2 (ConvBlock)            (None, 192, 64, 32)       9344      
_________________________________________________________________
conv3 (ConvBlock)            (None, 192, 64, 64)       18688     
_________________________________________________________________
pool (MaxPool2d)             (None, 96, 32, 64)        0         
=================================================================
Total params: 29,024
Trainable params: 28,768
Non-trainable params: 256
_________________________________________________________________
Summarizing features/stage1_47037845674768 ...
Model: "features/stage1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_4 (InputLayer)         [(None, 96, 32, 64)]      0         
_________________________________________________________________
stage1/unit_0_1 (ResNeStAUni (None, 96, 32, 256)       82976     
_________________________________________________________________
stage1/unit_0_2 (ResNeStAUni (None, 96, 32, 256)       77856     
_________________________________________________________________
stage1/unit_0_3 (ResNeStAUni (None, 96, 32, 256)       77856     
=================================================================
Total params: 238,688
Trainable params: 235,296
Non-trainable params: 3,392
_________________________________________________________________
Summarizing features/stage2_47038056687248 ...
Model: "features/stage2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_5 (InputLayer)         [(None, 96, 32, 256)]     0         
_________________________________________________________________
stage2/unit_1_1 (ResNeStAUni (None, 48, 16, 512)       407616    
_________________________________________________________________
stage2/unit_1_2 (ResNeStAUni (None, 48, 16, 512)       307264    
_________________________________________________________________
stage2/unit_1_3 (ResNeStAUni (None, 48, 16, 512)       307264    
_________________________________________________________________
stage2/unit_1_4 (ResNeStAUni (None, 48, 16, 512)       307264    
=================================================================
Total params: 1,329,408
Trainable params: 1,320,704
Non-trainable params: 8,704
_________________________________________________________________
Summarizing features/stage3_47038075441744 ...
Model: "features/stage3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_6 (InputLayer)         [(None, 48, 16, 512)]     0         
_________________________________________________________________
stage3/unit_2_1 (ResNeStAUni (None, 24, 8, 1024)       1618048   
_________________________________________________________________
stage3/unit_2_2 (ResNeStAUni (None, 24, 8, 1024)       1220736   
_________________________________________________________________
stage3/unit_2_3 (ResNeStAUni (None, 24, 8, 1024)       1220736   
_________________________________________________________________
stage3/unit_2_4 (ResNeStAUni (None, 24, 8, 1024)       1220736   
_________________________________________________________________
stage3/unit_2_5 (ResNeStAUni (None, 24, 8, 1024)       1220736   
_________________________________________________________________
stage3/unit_2_6 (ResNeStAUni (None, 24, 8, 1024)       1220736   
=================================================================
Total params: 7,721,728
Trainable params: 7,696,640
Non-trainable params: 25,088
_________________________________________________________________
Summarizing features/stage4_regional_branch_47038153257168 ...
Model: "features/stage4_regional_branch"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_7 (InputLayer)         [(None, 24, 8, 1024)]     0         
_________________________________________________________________
unit_3_1 (ResNeStAUnit)      (None, 24, 8, 2048)       6447360   
_________________________________________________________________
unit_3_2 (ResNeStAUnit)      (None, 24, 8, 2048)       4866304   
_________________________________________________________________
unit_3_3 (ResNeStAUnit)      (None, 24, 8, 2048)       4866304   
=================================================================
Total params: 16,179,968
Trainable params: 16,152,832
Non-trainable params: 27,136
_________________________________________________________________
Summarizing features/stage4_global_branch_47038077119696 ...
Model: "features/stage4_global_branch"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_7 (InputLayer)         [(None, 24, 8, 1024)]     0         
_________________________________________________________________
unit_3_1 (ResNeStAUnit)      (None, 24, 8, 2048)       6447360   
_________________________________________________________________
unit_3_2 (ResNeStAUnit)      (None, 24, 8, 2048)       4866304   
_________________________________________________________________
unit_3_3 (ResNeStAUnit)      (None, 24, 8, 2048)       4866304   
=================================================================
Total params: 16,179,968
Trainable params: 16,152,832
Non-trainable params: 27,136
_________________________________________________________________
Summarizing classification_model_47038165565328 ...
Model: "classification_model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_8 (InputLayer)            [(None, 2048)]       0                                            
__________________________________________________________________________________________________
input_9 (InputLayer)            [(None, 1024)]       0                                            
__________________________________________________________________________________________________
input_10 (InputLayer)           [(None, 1024)]       0                                            
__________________________________________________________________________________________________
batch_normalization (BatchNorma (None, 2048)         8192        input_8[0][0]                    
__________________________________________________________________________________________________
batch_normalization_1 (BatchNor (None, 1024)         4096        input_9[0][0]                    
__________________________________________________________________________________________________
batch_normalization_2 (BatchNor (None, 1024)         4096        input_10[0][0]                   
__________________________________________________________________________________________________
dense (Dense)                   (None, 751)          1538048     batch_normalization[0][0]        
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 751)          769024      batch_normalization_1[0][0]      
__________________________________________________________________________________________________
dense_2 (Dense)                 (None, 751)          769024      batch_normalization_2[0][0]      
__________________________________________________________________________________________________
activation_2 (Activation)       (None, 751)          0           dense[0][0]                      
__________________________________________________________________________________________________
activation_3 (Activation)       (None, 751)          0           dense_1[0][0]                    
__________________________________________________________________________________________________
activation_4 (Activation)       (None, 751)          0           dense_2[0][0]                    
==================================================================================================
Total params: 3,092,480
Trainable params: 3,084,288
Non-trainable params: 8,192
__________________________________________________________________________________________________
Initiating the image augmentor ...
Perform training ...
1
3
Loading weights from /project/zhanghong/FlipReID-master/Market1501.h5 ...
Freezing the whole model in the evaluation_only mode ...
Change the trainable property of training_model to False ...
Change the trainable property of convgroup1 to False ...
Change the trainable property of convgroup2 to False ...
Change the trainable property of convgroup1 to False ...
Change the trainable property of convgroup2 to False ...
Change the trainable property of convgroup1 to False ...
Change the trainable property of convgroup2 to False ...
Change the trainable property of convgroup1 to False ...
Change the trainable property of convgroup2 to False ...
Change the trainable property of convgroup1 to False ...
Change the trainable property of convgroup2 to False ...
Change the trainable property of convgroup1 to False ...
Change the trainable property of convgroup2 to False ...
Change the trainable property of convgroup1 to False ...
Change the trainable property of convgroup2 to False ...
Change the trainable property of convgroup1 to False ...
Change the trainable property of convgroup2 to False ...
Change the trainable property of convgroup1 to False ...
Change the trainable property of convgroup2 to False ...
Change the trainable property of convgroup1 to False ...
Change the trainable property of convgroup2 to False ...
Change the trainable property of convgroup1 to False ...
Change the trainable property of convgroup2 to False ...
Change the trainable property of convgroup1 to False ...
Change the trainable property of convgroup2 to False ...
Change the trainable property of convgroup1 to False ...
Change the trainable property of convgroup2 to False ...
Change the trainable property of convgroup1 to False ...
Change the trainable property of convgroup2 to False ...
Change the trainable property of convgroup1 to False ...
Change the trainable property of convgroup2 to False ...
Change the trainable property of convgroup1 to False ...
Change the trainable property of convgroup2 to False ...
Change the trainable property of convgroup1 to False ...
Change the trainable property of convgroup2 to False ...
Change the trainable property of convgroup1 to False ...
Change the trainable property of convgroup2 to False ...
Change the trainable property of convgroup1 to False ...
Change the trainable property of convgroup2 to False ...
loss 7.887027
tf_op_layer_RealDiv_2_loss 0.002644
tf_op_layer_RealDiv_3_loss 0.002606
tf_op_layer_RealDiv_4_loss 0.001227
classification_model_loss 0.036024
classification_model_1_loss 0.025743
classification_model_2_loss 0.019219
flipping 0.007067
global_ge_m_pooling2d_power 1.506939
global_ge_m_pooling2d_1_power 1.916795
global_ge_m_pooling2d_2_power 1.848862
1/1 - 2s - loss: 7.8870 - tf_op_layer_RealDiv_2_loss: 0.0026 - tf_op_layer_RealDiv_3_loss: 0.0026 - tf_op_layer_RealDiv_4_loss: 0.0012 - classification_model_loss: 0.0360 - classification_model_1_loss: 0.0257 - classification_model_2_loss: 0.0192 - flipping: 0.0071 - global_ge_m_pooling2d_power: 1.5069 - global_ge_m_pooling2d_1_power: 1.9168 - global_ge_m_pooling2d_2_power: 1.8489
All done!

Hi, i adjust epoch_num=2

**Comment by Peanut736** [comment]
I try test again, but encountered a deadlocks problem; did you try tf.data?

WARNING:tensorflow:multiprocessing can interact badly with TensorFlow, causing nondeterministic deadlocks. For high performance data pipelines tf.data is recommended.
W0226 14:52:20.675081 47088850867968 data_utils.py:522] multiprocessing can interact badly with TensorFlow, causing nondeterministic deadlocks. For high performance data pipelines tf.data is recommended.

**Comment by nixingyang** [comment]
- The issue seems to be related to `evaluate_testing_every_N_epochs`. Please set it to `1`.
- The code as it is should work fine on the specified version of TensorFlow, i.e., 2.2.3. There might be compatibility issues on the latest version. AFAIK, we have not tried the `tf.data` API.
