### ISSUE TITLE
Learning on my custom dataset

### ISSUE THREAD

**Issue by matsuKU** [nixingyang/FlipReID#15]
Hi,I'm matsuKU.
Thanks for your attractive work.

I have a question about when to learn using my custom dataset.
Currently, the number of people is 684.
The number of images is 66,794 for train, 66,071 for test, and 572 for query.
I started training on this dataset of mine, but it is not working.

Do you have the number of people and the number of images required for learning?

Thank you.

**Comment by nixingyang** [comment]
Hi,
Thanks for your interest in our work.

- Your own dataset is probably large enough to train a model from scratch. For comparison, MSMT17 has 32,621 training samples.
- It is not informative to merely claim "it is not working". Please elaborate on the issues you may have encountered.
- For the best performance, I suggest fine-tuning from a model trained on MSMT17.

All the best.
Xingyang

**Comment by matsuKU** [comment]
Thank you for your quick reply.

I was unable to train using my dataset, but was able to train a dataset that added my dataset to Market1501.
The number of images is comparable between Market1501 and my dataset. However, the number of identities registered in my dataset is about half of Market1501. Therefore, I think the number of identities is the reason why the training could not be done only with my dataset.
Below are the error when training with only my dataset.


`Epoch 00010: LearningRateScheduler reducing learning rate to 0.0003.
200/200 - 58s - loss: 224.7062 - tf.math.truediv_2_loss: 2.1126 - tf.math.truediv_3_loss: 0.7432 - tf.math.truediv_4_loss: 0.7973 - classification_model_loss: 1.2665 - classification_model_1_loss: 1.5288 - classification_model_2_loss: 1.9479 - flipping: 0.0262
Speed of feature extraction: 274.62 images per second.
cosine
Traceback (most recent call last):
  File "solution.py", line 1091, in <module>
    app.run(main)
  File "C:\Users\owner\anaconda3\envs\flip\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "C:\Users\owner\anaconda3\envs\flip\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "solution.py", line 1050, in main
    training_model.fit(x=train_generator,
  File "C:\Users\owner\anaconda3\envs\flip\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1145, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\Users\owner\anaconda3\envs\flip\lib\site-packages\tensorflow\python\keras\callbacks.py", line 428, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "solution.py", line 649, in on_epoch_end
    CMC_score_array, mAP_score = compute_CMC_mAP(
  File "C:\Users\owner\FlipReID\evaluation\metrics\__init__.py", line 39, in compute_CMC_mAP
    return evaluate_cy(distmat=distmat,
  File "evaluation\metrics\rank_cy.pyx", line 24, in evaluation.metrics.rank_cy.evaluate_cy
    cpdef evaluate_cy(distmat, q_pids, g_pids, q_camids, g_camids, max_rank, use_metric_cuhk03=False):
  File "evaluation\metrics\rank_cy.pyx", line 32, in evaluation.metrics.rank_cy.evaluate_cy
    return eval_market1501_cy(distmat, q_pids, g_pids, q_camids, g_camids, max_rank)
  File "evaluation\metrics\rank_cy.pyx", line 228, in evaluation.metrics.rank_cy.eval_market1501_cy
    assert num_valid_q > 0, 'Error: all query identities do not appear in gallery'
AssertionError: Error: all query identities do not appear in gallery`

Thank you.

**Comment by nixingyang** [comment]
The error message is self-explanatory, i.e., `all query identities do not appear in gallery`. The issue is within the validation set.
The most likely explanation is that images of any query identity in the validation set should also be found in the gallery. Please check how the original/your validation sets are defined and what the differences are.
Xingyang

**Comment by matsuKU** [comment]
Thank you for answering my question.
I would try to check the difference between the original validation set and mine.
If I have any more questions I will ask you.

Thank you very much.
