### ISSUE TITLE
Test on my data

### ISSUE THREAD

**Issue by kazuki-can** [nixingyang/FlipReID#3]
Hi again.
Thank you a lot for what you have helped me.
I have one question about this model.
How can I use my data to this model?
I tried this code below but I couldn't find the alternative of "preprocess_input" function.
`root_folder_path = os.path.expanduser("~/FlipReID")
        image_file_path_list = [
            os.path.join(root_folder_path, item) for item in [
                "img00004.png",
                "img00019.png",
                "img00063.png"
            ]
        ]
        image_content_list = [
            read_image_file(image_file_path, input_shape)
            for image_file_path in image_file_path_list
        ]
        image_content_array = preprocess_input(np.array(image_content_list))
        
        first, second, third = inference_model.predict(image_content_array,
                                                        batch_size=batch_size)
        
        distance_matrix = test_evaluator_callback.compute_distance_matrix(
            query_image_features=[first],
            gallery_image_features=[second, third],
            metric="cosine",
            use_re_ranking=use_re_ranking)
        print(f'distance[0]:{distance_matrix[0][0]}\ndistance[1]:{distance_matrix[0][1]}\n')
        
        assert False, distance_matrix`

**Comment by kazuki-can** [comment]
I have one more question.
The method with Figure2 (a) and (c) in the paper gives me the same results as Adaptive L2 Regularization?

**Comment by nixingyang** [comment]
Hi,

- I have integrated the `preprocess_input` function as [part](https://github.com/nixingyang/FlipReID/blob/427d7e184c2d2b804c49b433838012aeb6b43aec/applications/__init__.py#L53-L57) of the model. You do not need to call it explicitly.
- In the [AdaptiveL2Regularization](https://arxiv.org/abs/2007.07875) work, we use Figure 2.a in training, and Figure 2.c and Figure 2.d in inference. Additionally, we have also made substantial improvements in this [FlipReID](https://arxiv.org/abs/2105.05639) work. It is advisable to use `FlipReID` from now on.

Xingyang

**Comment by kazuki-can** [comment]
Hi , thank you for the answer.
I wrote the code like below
`root_folder_path = os.path.expanduser("~/FlipReID")
        image_file_path_list = [
            os.path.join(root_folder_path, item) for item in [
                "img00004.png",
                "img00019.png",
                "img00063.png"
            ]
        ]
        image_content_list = [
            read_image_file(image_file_path, input_shape)
            for image_file_path in image_file_path_list
        ]

        first, second, third = inference_model.predict(image_content_list,
                                                        batch_size=batch_size)

        distance_matrix = test_evaluator_callback.compute_distance_matrix(
            query_image_features=[first],
            gallery_image_features=[second, third],
            metric="cosine",
            use_re_ranking=use_re_ranking)
        print(f'distance[0]:{distance_matrix[0][0]}\ndistance[1]:{distance_matrix[0][1]}\n')`
But I got an error saying 
`Traceback (most recent call last):
  File "solution.py", line 935, in <module>
    app.run(main)
  File "C:\Users\owner\anaconda3\envs\flip\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "C:\Users\owner\anaconda3\envs\flip\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "solution.py", line 876, in main
    first, second, third = inference_model.predict(image_content_list,
  File "C:\Users\owner\anaconda3\envs\flip\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1629, in predict
    tmp_batch_outputs = self.predict_function(iterator)
  File "C:\Users\owner\anaconda3\envs\flip\lib\site-packages\tensorflow\python\eager\def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\owner\anaconda3\envs\flip\lib\site-packages\tensorflow\python\eager\def_function.py", line 871, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "C:\Users\owner\anaconda3\envs\flip\lib\site-packages\tensorflow\python\eager\def_function.py", line 725, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "C:\Users\owner\anaconda3\envs\flip\lib\site-packages\tensorflow\python\eager\function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\owner\anaconda3\envs\flip\lib\site-packages\tensorflow\python\eager\function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\owner\anaconda3\envs\flip\lib\site-packages\tensorflow\python\eager\function.py", line 3196, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "C:\Users\owner\anaconda3\envs\flip\lib\site-packages\tensorflow\python\framework\func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\owner\anaconda3\envs\flip\lib\site-packages\tensorflow\python\eager\def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Users\owner\anaconda3\envs\flip\lib\site-packages\tensorflow\python\framework\func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    C:\Users\owner\anaconda3\envs\flip\lib\site-packages\tensorflow\python\keras\engine\training.py:1478 predict_function  *
        return step_function(self, iterator)
    C:\Users\owner\anaconda3\envs\flip\lib\site-packages\tensorflow\python\keras\engine\training.py:1468 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\owner\anaconda3\envs\flip\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\owner\anaconda3\envs\flip\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\owner\anaconda3\envs\flip\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\owner\anaconda3\envs\flip\lib\site-packages\tensorflow\python\keras\engine\training.py:1461 run_step  **
        outputs = model.predict_step(data)
    C:\Users\owner\anaconda3\envs\flip\lib\site-packages\tensorflow\python\keras\engine\training.py:1434 predict_step
        return self(x, training=False)
    C:\Users\owner\anaconda3\envs\flip\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:998 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    C:\Users\owner\anaconda3\envs\flip\lib\site-packages\tensorflow\python\keras\engine\input_spec.py:204 assert_input_compatibility
        raise ValueError('Layer ' + layer_name + ' expects ' +

    ValueError: Layer inference_model expects 1 input(s), but it received 3 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(64, 128, 3) dtype=uint8>, <tf.Tensor 'IteratorGetNext:1' shape=(64, 128, 3) dtype=uint8>, <tf.Tensor 'IteratorGetNext:2' shape=(64, 128, 3) dtype=uint8>]`

How should I write the code?
I want to use this model and see how it works as soon as possible,so if you teach me what I should write, I will be so happy.

Thank you.

**Comment by nixingyang** [comment]
Kindly check the following snippet.
```python
apply_stacking = lambda x: np.hstack(x) if isinstance(x, list) else x
feature_array = apply_stacking(
    inference_model.predict(x=np.array(image_content_list,
                                        dtype=np.float32),
                            batch_size=batch_size))
```
Xingyang

**Comment by kazuki-can** [comment]
Thank you so much.
It works now.
Since I asked you how to fix the previous issue, I've made you spend your time on my problems a lot.
I do appreciate you.

**Comment by nixingyang** [comment]
No problem. Feel free to contact me if you need any further assistance.
Xingyang

**Comment by kazuki-can** [comment]
Hello again.
I have tried this model in many ways.
And I have two questions.
First, in evaluation, do I have to input a picture , a similar picture to the first one and not similar to the first one?
The model didn't work well when there are some people looking similar to each other.

Second, I want to train this model with pictures whose background is removed and masked by one color. Have you ever tried this way ?
If you have done before, can I have your opinion ?

**Comment by nixingyang** [comment]
Hi,
You can feed any images as you like. Images do not have to be similar or dissimilar to each other. Person re-identification is still an unsolved challenge, and our model is imperfect. It is expected that a model could not distinguish among similar-looking samples.
I have done similar experiments using person segmentation, and this idea does not help. You could review other related papers in this research direction.
Xingyang

**Comment by kazuki-can** [comment]
Thank you for replying.
Is the dataset especially Market1501 that has person segmentation in public ?

**Comment by nixingyang** [comment]
Based on my understanding, you have to process the dataset yourself. There is no official segmented dataset.
Xingyang

**Comment by kazuki-can** [comment]
Alright, thank you for helping me.
Kazuki-can
