### ISSUE TITLE
Question about speed

### ISSUE THREAD

**Issue by ShinYoung-hwan** [nixingyang/FlipReID#4]
It is a very interesting work!
I have a question regarding speed.
Can using FlipReid make inference slower than before?

**Comment by nixingyang** [comment]
The proposed FlipReID method will not reduce the inference speed.
In the end, you still get a feature extractor that shares the same architecture as the baseline method.
The main contribution is that the retrieval performance would be improved in the case that test-time augmentation is used.
Xingyang
