### ISSUE TITLE
复现时遇到的问题

### ISSUE THREAD

**Issue by LiYanchao-lab** [nixingyang/FlipReID#5]
我跑到第10轮时，
 Epoch 00010: LearningRateScheduler reducing learning rate to 0.0002. Epoch 10/20 Speed of feature extraction: 1274.98 images per second. Traceback (most recent call last):   File "solution.py", line 924, in <module>     app.run(main)   File "D:\ProgramData\anaconda3\envs\fri\lib\site-packages\absl\app.py", line 312, in run     _run_main(main, args)   File "D:\ProgramData\anaconda3\envs\fri\lib\site-packages\absl\app.py", line 258, in _run_main     sys.exit(main(argv))   File "solution.py", line 883, in main     training_model.fit(x=train_generator,   File "D:\ProgramData\anaconda3\envs\fri\lib\site-packages\tensorflow\python\keras\engine\training.py", line 66, in _method_wrapper     return method(self, *args, **kwargs)   File "D:\ProgramData\anaconda3\envs\fri\lib\site-packages\tensorflow\python\keras\engine\training.py", line 876, in fit     callbacks.on_epoch_end(epoch, epoch_logs)   File "D:\ProgramData\anaconda3\envs\fri\lib\site-packages\tensorflow\python\keras\callbacks.py", line 365, in on_epoch_end     callback.on_epoch_end(epoch, logs)   File "solution.py", line 637, in on_epoch_end     CMC_score_array, mAP_score = compute_CMC_mAP(   File "D:\iwork\github\FlipReID\evaluation\metrics\__init__.py", line 39, in compute_CMC_mAP     return evaluate_cy(distmat=distmat,   File "evaluation\metrics\rank_cy.pyx", line 24, in evaluation.metrics.rank_cy.evaluate_cy     cpdef evaluate_cy(distmat, q_pids, g_pids, q_camids, g_camids, max_rank, use_metric_cuhk03=False):   File "evaluation\metrics\rank_cy.pyx", line 32, in evaluation.metrics.rank_cy.evaluate_cy     return eval_market1501_cy(distmat, q_pids, g_pids, q_camids, g_camids, max_rank) ValueError: Buffer dtype mismatch, expected 'long' but got 'long long' ，出现上面问题，而且前几轮的loss都是nan,这是怎么回事啊？刚入门小白一脸懵，请问怎么解决呢？

**Comment by nixingyang** [comment]
这个大概率是Windows环境问题，而这份代码仅在Linux环境下测试过。
如果这个问题在Linux环境下依然存在，请告知我。

**Comment by LiYanchao-lab** [comment]
> 这个大讨论是Windows环境问题，而这篇代码仅在Linux环境下测试过。
> 如果问题在Linux环境下测试过，请告知我。

非常感谢您的回复，我在Ubuntu下重试了，得到的loss仍然是nan，可能的原因会是什么呢？

**Comment by nixingyang** [comment]
1，确认参考了[environment](https://github.com/nixingyang/FlipReID#environment)安装特定版本的包；
2，可以提供详细的日志。
