### ISSUE TITLE
Deadlock in test phase

### ISSUE THREAD

**Issue by oliver8459** [nixingyang/FlipReID#7]
Deadlock will happen sometimes in test phase if I use multi gpus.
"WARNING:tensorflow:multiprocessing can interact badly with TensorFlow, causing nondeterministic deadlocks. For high performance data pipelines tf.data is recommended."

**Comment by nixingyang** [comment]
FYI, current implementation has not been optimized for the multi-GPU use case. If this issue is causing problems, you may switch to tf.data as suggested in the warning message.
Xingyang
